package com.themis.userinfo.entity;

import java.io.Serializable;
import lombok.Builder;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 *
 * @mbg.generated do_not_delete_during_merge 2017-10-18
 */
@Data
@Builder
public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated 2017-10-18
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbg.generated 2017-10-18
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.suid
     *
     * @mbg.generated 2017-10-18
     */
    private String suid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.token
     *
     * @mbg.generated 2017-10-18
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sign_in_name
     *
     * @mbg.generated 2017-10-18
     */
    private String signInName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sign_in_password
     *
     * @mbg.generated 2017-10-18
     */
    private String signInPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.salt
     *
     * @mbg.generated 2017-10-18
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated 2017-10-18
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.enabled
     *
     * @mbg.generated 2017-10-18
     */
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_url
     *
     * @mbg.generated 2017-10-18
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_type
     *
     * @mbg.generated 2017-10-18
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated 2017-10-18
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated 2017-10-18
     */
    private static final long serialVersionUID = 1L;
}